<h1>A 403 error occurred</h1>

<p>You are not allowed to access this resource</p>

<?php if( empty($this->lmcUserIdentity()) ):?>
<a class="btn btn-primary" href="<?=$this->url('lmcuser/login') ?>" >Login</a>
<?php endif;?>
<h2>Details</h2>

<?php
use LmcRbacMvc\Guard\GuardInterface;

switch ($this->error) {
    case GuardInterface::GUARD_UNAUTHORIZED:
        echo '<p>Request was blocked by a LmcRbacMvc guard</p>';
        break;
}
